#
# Copyright (C) BABEC. All rights reserved.
# Copyright (C) THL A29 Limited, a Tencent company. All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

chain_id: {chain_id}    # 链标识
version: v2.0.0         # 链版本
sequence: 1             # 配置版本
auth_type: "identity"   # 认证类型

crypto:
  hash: SHA256

# 合约支持类型的配置
contract:
  enable_sql_support: false # 此处若为true，则chainmaker.yml中则需配置storage.statedb_config.provider=sql，否则无法启动

# 交易、区块相关配置
block:
  tx_timestamp_verify: true # 是否需要开启交易时间戳校验
  tx_timeout: 600  # 交易时间戳的过期时间(秒)
  block_tx_capacity: 100  # 区块中最大交易数
  block_size: 10  # 区块最大限制，单位MB
  block_interval: 2000 # 出块间隔，单位:ms

# core模块
core:
  tx_scheduler_timeout: 10 #  [0, 60] 交易调度器从交易池拿到交易后, 进行调度的时间
  tx_scheduler_validate_timeout: 10 # [0, 60] 交易调度器从区块中拿到交易后, 进行验证的超时时间

# snapshot module
snapshot:
  enable_evidence: false # enable the evidence support 

# scheduler module
scheduler:
  enable_evidence: false # enable the evidence support

#共识配置
consensus:
  # 共识类型(0-SOLO,1-TBFT,2-MBFT,3-HOTSTUFF,4-RAFT,5-DPOS,10-POW)
  type: {consensus_type}
  # 共识节点列表，组织必须出现在trust_roots的org_id中，每个组织可配置多个共识节点，节点地址采用libp2p格式
  # 其中node_id为chainmaker.yml中 node.cert_file证书对应的nodeid
  nodes:
    - org_id: "{org1_id}"
      node_id:
        - "{org1_peerid}"
    - org_id: "{org2_id}"
      node_id:
        - "{org2_peerid}"
    - org_id: "{org3_id}"
      node_id:
        - "{org3_peerid}"
    - org_id: "{org4_id}"
      node_id:
        - "{org4_peerid}"
    - org_id: "{org5_id}"
      node_id:
        - "{org5_peerid}"
    - org_id: "{org6_id}"
      node_id:
        - "{org6_peerid}"
    - org_id: "{org7_id}"
      node_id:
        - "{org7_peerid}"
    - org_id: "{org8_id}"
      node_id:
        - "{org8_peerid}"
    - org_id: "{org9_id}"
      node_id:
        - "{org9_peerid}"
    - org_id: "{org10_id}"
      node_id:
        - "{org10_peerid}"
    - org_id: "{org11_id}"
      node_id:
        - "{org11_peerid}"
    - org_id: "{org12_id}"
      node_id:
        - "{org12_peerid}"
    - org_id: "{org13_id}"
      node_id:
        - "{org13_peerid}"
    - org_id: "{org14_id}"
      node_id:
        - "{org14_peerid}"
    - org_id: "{org15_id}"
      node_id:
        - "{org15_peerid}"
    - org_id: "{org16_id}"
      node_id:
        - "{org16_peerid}"
  ext_config: # 扩展字段，记录难度、奖励等其他类共识算法配置
    - key: aa
      value: chain01_ext11
  dpos_config: # DPoS
    #ERC20合约配置
    - key: erc20.total
      value: "{erc20_total}"
    - key: erc20.owner
      value: "{org1_peeraddr}"
    - key: erc20.decimals
      value: "18"
    - key: erc20.account:DPOS_STAKE
      value: "{erc20_total}"
    #Stake合约配置
    - key: stake.minSelfDelegation
      value: "2500000"
    - key: stake.epochValidatorNum
      value: "{epochValidatorNum}"
    - key: stake.epochBlockNum
      value: "10"
    - key: stake.completionUnbondingEpochNum
      value: "1"
    - key: stake.candidate:{org1_peeraddr}
      value: "2500000"
    - key: stake.candidate:{org2_peeraddr}
      value: "2500000"
    - key: stake.candidate:{org3_peeraddr}
      value: "2500000"
    - key: stake.candidate:{org4_peeraddr}
      value: "2500000"
    - key: stake.candidate:{org5_peeraddr}
      value: "2500000"
    - key: stake.candidate:{org6_peeraddr}
      value: "2500000"
    - key: stake.candidate:{org7_peeraddr}
      value: "2500000"
    - key: stake.candidate:{org8_peeraddr}
      value: "2500000"
    - key: stake.candidate:{org9_peeraddr}
      value: "2500000"
    - key: stake.candidate:{org10_peeraddr}
      value: "2500000"
    - key: stake.candidate:{org11_peeraddr}
      value: "2500000"
    - key: stake.candidate:{org12_peeraddr}
      value: "2500000"
    - key: stake.candidate:{org13_peeraddr}
      value: "2500000"
    - key: stake.candidate:{org14_peeraddr}
      value: "2500000"
    - key: stake.candidate:{org15_peeraddr}
      value: "2500000"
    - key: stake.candidate:{org16_peeraddr}
      value: "2500000"
    - key: stake.nodeID:{org1_peeraddr}
      value: "{org1_peerid}"
    - key: stake.nodeID:{org2_peeraddr}
      value: "{org2_peerid}"
    - key: stake.nodeID:{org3_peeraddr}
      value: "{org3_peerid}"
    - key: stake.nodeID:{org4_peeraddr}
      value: "{org4_peerid}"
    - key: stake.nodeID:{org5_peeraddr}
      value: "{org5_peerid}"
    - key: stake.nodeID:{org6_peeraddr}
      value: "{org6_peerid}"
    - key: stake.nodeID:{org7_peeraddr}
      value: "{org7_peerid}"
    - key: stake.nodeID:{org8_peeraddr}
      value: "{org8_peerid}"
    - key: stake.nodeID:{org9_peeraddr}
      value: "{org9_peerid}"
    - key: stake.nodeID:{org10_peeraddr}
      value: "{org10_peerid}"
    - key: stake.nodeID:{org11_peeraddr}
      value: "{org11_peerid}"
    - key: stake.nodeID:{org12_peeraddr}
      value: "{org12_peerid}"
    - key: stake.nodeID:{org13_peeraddr}
      value: "{org13_peerid}"
    - key: stake.nodeID:{org14_peeraddr}
      value: "{org14_peerid}"
    - key: stake.nodeID:{org15_peeraddr}
      value: "{org15_peerid}"
    - key: stake.nodeID:{org16_peeraddr}
      value: "{org16_peerid}"

# 信任组织和根证书
trust_roots:
  - org_id: "{org1_id}"
    root:
      - "./certs/ca/{org1_id}/ca.crt"
  - org_id: "{org2_id}"
    root: 
      - "./certs/ca/{org2_id}/ca.crt"
  - org_id: "{org3_id}"
    root:
      - "./certs/ca/{org3_id}/ca.crt"
  - org_id: "{org4_id}"
    root:
      - "./certs/ca/{org4_id}/ca.crt"
  - org_id: "{org5_id}"
    root:
      - "./certs/ca/{org5_id}/ca.crt"
  - org_id: "{org6_id}"
    root:
      - "./certs/ca/{org6_id}/ca.crt"
  - org_id: "{org7_id}"
    root:
      - "./certs/ca/{org7_id}/ca.crt"
  - org_id: "{org8_id}"
    root:
      - "./certs/ca/{org8_id}/ca.crt"
  - org_id: "{org9_id}"
    root:
      - "./certs/ca/{org9_id}/ca.crt"
  - org_id: "{org10_id}"
    root:
      - "./certs/ca/{org10_id}/ca.crt"
  - org_id: "{org11_id}"
    root:
      - "./certs/ca/{org11_id}/ca.crt"
  - org_id: "{org12_id}"
    root:
      - "./certs/ca/{org12_id}/ca.crt"
  - org_id: "{org13_id}"
    root:
      - "./certs/ca/{org13_id}/ca.crt"
  - org_id: "{org14_id}"
    root:
      - "./certs/ca/{org14_id}/ca.crt"
  - org_id: "{org15_id}"
    root:
      - "./certs/ca/{org15_id}/ca.crt"
  - org_id: "{org16_id}"
    root:
      - "./certs/ca/{org16_id}/ca.crt"

# 证书库
#trust_members:
#  - member_info: ""
#    org_id: ""
#    role: "consensus"
#    node_id:  ""
#  - member_info: ""
#    org_id: ""
#    role: "common"
#    node_id:  ""

# 权限配置（只能整体添加、修改、删除）
resource_policies:
  - resource_name: CHAIN_CONFIG-NODE_ID_UPDATE
    policy:
      rule: SELF # 规则（ANY，MAJORITY...，全部大写，自动转大写）
      org_list: # 组织名称（组织名称，区分大小写）
      role_list: # 角色名称（role，自动转大写）
        - admin
  - resource_name: CHAIN_CONFIG-TRUST_ROOT_ADD
    policy:
      rule: MAJORITY
      org_list:
      role_list:
        - admin
  - resource_name: CHAIN_CONFIG-CERTS_FREEZE
    policy:
      rule: ANY
      org_list:
      role_list:
        - admin
